version: "3"
services:

    node_inkeby:
        container_name: node
        build:
            context: ./geth_rinkeby_node
                # volumes
        volumes:
            - ".:/home/app/geth_rinkeby_node"
        # command: >
        #     bash
        stdin_open: true # docker run -i
        tty: true # docker run -t
        ports : 
            - 8545:8545
            - 30303:30303
            - 3334:3334